package com.griffith.models

import org.osmdroid.util.GeoPoint
import java.text.SimpleDateFormat
import java.time.Instant
import java.util.Locale
import java.util.UUID

//a journal entry
data class JournalItem(
    //generate random id
    val id: String = UUID.randomUUID().toString(),

    val title: String,
    val description: String,

    //Run, walk, cycle, etc
    val journeyType: String,

    //OPTIONAL FIELDS - only has data if the journal entry was generated by the journey tracker

    //start and end times are stored as longs
    val startTime: Long = 0L,
    val endTime: Long = 0L,

    //start and positions are stored using GeoPoints (latitude, longitude)
    val startPosition: GeoPoint? = null,
    val endPosition: GeoPoint? = null,

    //date format
    val dateFormat: SimpleDateFormat = SimpleDateFormat("MMM dd, yyyy, HH:mm", Locale.getDefault())
)
