package com.griffith.models

import java.time.Instant

//a journal entry
data class JournalItem(
    val title: String,

    val description: String,

    //Run, walk, cycle, etc
    val journeyType: String,

    //OPTIONAL FIELDS - only has data if the journal entry was generated by the journey tracker

    //start and end times are stored as longs
    val startTime: Long = 0L,
    val endTime: Long = 0L,

    //start and positions are stored using a custom data class - Coordinate (latitude, longitude)
    val startPosition: Coordinate? = null,
    val endPosition: Coordinate? = null
)
